export default 
  [
    { title:'Crystal Pier Race',
      description:'The Crystal Pier Outrigger Canoe Race is a Southern California Outrigger Racing Association Race, hosted by Hanohano Canoe Club in San Diego, CA. The race draws 1500+ participants annually who battle in a 6-mile short course, novice and kid’s race as well as a 10-mile men, women and coed races in six person outrigger canoes.',
      date:'2nd weekend of May',
      location:'Crown Beach, San Diego, CA',
      more:"/raceInfo/crystalPier.pdf",
      img:"/images/events_crystal_pier.jpg",
      id:'cp'
    },
    {title:'Kahahamoku Klassic',
      description:'Marina Outrigger Canoe Club will host its annual Kahanamoku Klassic Outrigger Canoe Race in Marina del Rey, California on Saturday, June 1. The 6-man outrigger canoe race, overseen by the Southern California Outrigger Racing Association, draws some 2,000 participants from around the state, as well as Arizona, Nevada, Texas, Hawaii and Tahiti.',
      date:'1st weekend of June',
      location:"Mother's Beach, Marina Del Rey, CA",
      more:"/raceInfo/MDR.pdf",
      img:"/images/events_mdr2.jpg",
      id:'mdr'
    },
    {title:'Iron Champs',
      description:"Hosted by Kai Elua OCC, this race marks the end of Iron season.  Races include a 6 mile short course as well as a 12 mile long course along Mariner's Point in San Diego, CA.",
      date:'3rd weekend of June',
      location:"Mariner's Point, San Diego, CA",
      more:"/raceInfo/IronChamps.pdf",
      img:"/images/events_irons.jpg",
      id:'irons'  
    },
    {title:'Whitey Harrison Classic',
      description:"The Whitey Harrison Classic is a 20-Mile, 9-Man Outrigger race hosted by Dana Outrigger every August. The race was first run in July of 1971 from Newport to Dana Point Harbor as part of the Harbor’s Opening Ceremonies. Now approaching its 46th Annual, the race now runs from just outside the mouth of Dana Point Harbor to Main Beach in Laguna and back. This event draws more than 900 competitors who compete in over 19 divisions and range in age from 12 to 70 years old. The festivities take place at Doheny State Beach. ",
      date:'2nd weekend of August',
      location:"Doheny State Park, Dana Point, CA",
      more:"/raceInfo/Dana.pdf",
      img:"/images/events_dana.jpg",
      id:'dana'
    },    
    {title:'Paopao',
      description:"The 2nd series of 9 man distances for SCORA.  This is a 22 mile 9-man change race held in Oceanside, CA.  Paddlers from all over California will take part in a 21-mile race and get ready for the upcoming 34-mile Catalina Crossing, which is also part of the Southern California Outrigger Racing Association (SCORA) race series. Crews consist of nine paddlers and a chase boat. The nine-man crews allow six riders in the boat. Paddlers are periodically rotated in and out of the canoe at key intervals in the race to maintain performance.  Teams will take off in both Women’s and Men’s heats with all age groups starting at the same time. The youngest paddlers on the boat determine a team’s age group category. You can expect the competition to range from sixteen-year-old keikis to sixty-year-old masters – Many who compete have been watermen their entire lives. Paddlers must maintain a high degree of physical fitness and precise teamwork.",
      date:'4th weekend of August',
      location:"Oceanside Harbor, Oceanside, CA",
      more:"/raceInfo/oceanside.pdf",
      img:"/images/events_oceanside.jpg",
      id:'oceanside'
    },
    {title:'Catalina Crossing',
      description:"The U.S. Outrigger Championships send teams and their all-important paddles between Newport Beach and Santa Catalina Island over the first weekend in September. The women's teams and coed team's head out on Saturday, for a 26-mile route; the men are in the outriggers on Sunday with 30 miles to face. Call it a thrilling experience for the participants, of course, but also for anyone standing on shore or out on a boat who happens to witness it. Outriggers have a long and storied history with strong ties to Polynesia and Hawaii; call it a beautiful and rarer sight to see the streamlined vessels skimming waves off Southern California shores.",
      date:'1st or 2nd weekend of September',
      location:"Newport Beach to Catalina Island, Catalina Island to Newport Beach",
      more:"http://www.catalinacrossing.org/",
      img:"/images/events_catalina.jpg",
      id:'catalina'
    },    
    {title:'Queen Lili`uokalani Canoe Race',
      description:"What is now the World's Largest Long Distance Canoe Race was actually started in 1972 simply to fulfill a need. The race really began as a way to train for the grueling Na Wahine O Ke Kai (Women) and the Molokai Hoe (Men) long distance canoe races from the island of Molokai to the island of Oahu. Named in honor of the last reigning monarch of Hawaii, Queen Lili'uokalani, the first race fell on the Queen's birthday, September 2. Since those early beginnings, the race has grown tremendously. It is now host to over two thousand five hundred paddlers from all over the world - Australia, New Zealand, Japan, Hong Kong, Florida, California and Canada - just to name a few.",
      date:'Labor Day Weekend',
      location:"Kailua-Kona, HI",
      more:"https://www.qlcanoerace.com",
      img:"/images/events_liliuokalani.jpg",
      id:'liliuo'
    },                 
    { title:'Aloha Fest',
      description:'Take an island vacation without leaving Tempe at the Arizona Aloha Festival, March 14-15, 2020. This free family event celebrates Hawaiian, Tahitian, Samoan and other South Pacific cultures through dance and musical performances, food, kid’s crafts and more fun at Tempe Beach Park. You’ll find lots of great shopping at two marketplace areas and delicious and tempting island foods at two food courts. Team Arizona typically has a booth in the Heritage Village displaying our canoe and recruiting paddlers by sharing our stories and experiences of various races in California, Hawaii and other locations',
      date:'2nd weekend of March',
      location:'Tempe Beach Park, Tempe, AZ',
      more:"http://www.azalohafest.org",
      img:"/images/events_aloha_fest.jpg",
      id:'aloha'
    },
    { title:'Iron Man Volunteering',
      description:"The Arizona Ironman triathlon is a long-distance triathlon race organized by the World Triathlon Corporation, consisting of a 2.4-mile swim, a 112-mile bicycle ride and a marathon 26.22-mile run, raced in that order. Team Arizona typically volunteers as a Race Station, Bike in/out Station and Women's Change Station",
      date:'3rd weekend of November',
      location:'Tempe Beach Park, Tempe, AZ',
      more:"http://www.ironman.com",
      img:"/images/events_ironman.jpg",
      id:'ironman'
    }
  ]